export const ventusRadiant = [
  { address: "version_choice({0x0, 0xD751AE}, game_version)", name: "Soothing Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD751B6}, game_version)", name: "Pulsing Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD751BE}, game_version)", name: "Ether", prefix: "6" },
  { address: "version_choice({0x0, 0xD751C6}, game_version)", name: "Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD751CE}, game_version)", name: "Panacea", prefix: "6" },
  { address: "version_choice({0x0, 0xD751D6}, game_version)", name: "Fira", prefix: "6" },
  { address: "version_choice({0x0, 0xD751DE}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD751E6}, game_version)", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "version_choice({0x0, 0xD751A6}, game_version)", name: "Counter Rush", prefix: "6" },
  { address: "version_choice({0x0, 0xD7521E}, game_version)", name: "Block Recipe", prefix: "6" },
  { address: "version_choice({0x0, 0xD751EE}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD751F6}, game_version)", name: "Binding Strike", prefix: "6" },
  { address: "version_choice({0x0, 0xD751FE}, game_version)", name: "Wellspring Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD75206}, game_version)", name: "Slow", prefix: "6" },
  { address: "version_choice({0x0, 0xD75216}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD7520E}, game_version)", name: "Freeze Raid", prefix: "6" },
];
