export const ventusCastle = [
  { address: "version_choice({0x0, 0xD750A6}, game_version)", name: "Map (Castle of Dreams)", prefix: "3" },
  { address: "version_choice({0x0, 0xD750AE}, game_version)", name: "Stund Edge", prefix: "3" },
  { address: "version_choice({0x0, 0xD750B6}, game_version)", name: "Magic Recipe", prefix: "3" },
  { address: "version_choice({0x0, 0xD750BE}, game_version)", name: "Potion", prefix: "3" },
  { address: "version_choice({0x0, 0xD750C6}, game_version)", name: "Thunderstorm", prefix: "3" },
  { address: "version_choice({0x0, 0xD750CE}, game_version)", name: "Ether", prefix: "3" },
  { address: "version_choice({0x0, 0xD750D6}, game_version)", name: "Pulsing Crystal", prefix: "3" },
  { address: "version_choice({0x0, 0xD750DE}, game_version)", name: "Potion", prefix: "3" },
  { address: "version_choice({0x0, 0xD75106}, game_version)", name: "Hungry Crystal", prefix: "3" },
  { address: "version_choice({0x0, 0xD750E6}, game_version)", name: "Zero Gravity", prefix: "3" },
  { address: "version_choice({0x0, 0xD750EE}, game_version)", name: "Balloon Letter", prefix: "3" },
  { address: "version_choice({0x0, 0xD750F6}, game_version)", name: "Blizzard", prefix: "3" },
  { address: "version_choice({0x0, 0xD750FE}, game_version)", name: "Fleeting Crystal", prefix: "3" },
];
