export const ventusEnchanted = [
  { address: "version_choice({0x0, 0xD75116}, game_version)", name: "Balloon Letter", prefix: "4" },
  { address: "version_choice({0x0, 0xD7511E}, game_version)", name: "Soothing Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD75126}, game_version)", name: "Cure", prefix: "4" },
  { address: "version_choice({0x0, 0xD7512E}, game_version)", name: "Wellspring Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD7519E}, game_version)", name: "Absolute Zero", prefix: "4" },
  { address: "version_choice({0x0, 0xD7510E}, game_version)", name: "Hi-Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD75136}, game_version)", name: "Fleeting Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD7513E}, game_version)", name: "Tornado Strike", prefix: "4" },
  { address: "version_choice({0x0, 0xD7514E}, game_version)", name: "Wellspring Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD7515E}, game_version)", name: "Hungry Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD75176}, game_version)", name: "Magnet", prefix: "4" },
  { address: "version_choice({0x0, 0xD75196}, game_version)", name: "Hi-Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD75146}, game_version)", name: "Ether", prefix: "4" },
  { address: "version_choice({0x0, 0xD75156}, game_version)", name: "Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD75166}, game_version)", name: "Map (Enchanted Dominion)", prefix: "4" },
  { address: "version_choice({0x0, 0xD7516E}, game_version)", name: "Hi-Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD7517E}, game_version)", name: "Thunder", prefix: "4" },
  { address: "version_choice({0x0, 0xD75186}, game_version)", name: "Hi-Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD7518E}, game_version)", name: "Sleep", prefix: "4" },
];
