export const ventusDisney = [
  { address: "version_choice({0x0, 0xD7524E}, game_version)", name: "Map (Disney Town)", prefix: "C" },
  { address: "version_choice({0x0, 0xD75256}, game_version)", name: "Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD75226}, game_version)", name: "Superglide", prefix: "C" },
  { address: "version_choice({0x0, 0xD7522E}, game_version)", name: "Reversal Slash", prefix: "C" },
  { address: "version_choice({0x0, 0xD75236}, game_version)", name: "Slot Edge", prefix: "C" },
  { address: "version_choice({0x0, 0xD7523E}, game_version)", name: "Shimmering Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD75246}, game_version)", name: "Stop", prefix: "C" },
  { address: "version_choice({0x0, 0xD7525E}, game_version)", name: "Mega-Ether", prefix: "C" },
  { address: "version_choice({0x0, 0xD75266}, game_version)", name: "Mega-Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD7526E}, game_version)", name: "Chaos Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD75276}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD7527E}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD75296}, game_version)", name: "Mega-Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD75286}, game_version)", name: "Panacea", prefix: "C" },
  { address: "version_choice({0x0, 0xD752AE}, game_version)", name: "Action Recipe", prefix: "C" },
  { address: "version_choice({0x0, 0xD7528E}, game_version)", name: "Aerial Slam", prefix: "C" },
  { address: "version_choice({0x0, 0xD7529E}, game_version)", name: "Break Time", prefix: "C" },
  { address: "version_choice({0x0, 0xD752A6}, game_version)", name: "Wellspring Crystal", prefix: "C" },
];
