export const ventusSpace = [
  { address: "version_choice({0x0, 0xD752DE}, game_version)", name: "Abounding Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD752E6}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD752EE}, game_version)", name: "Pulsing Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD752F6}, game_version)", name: "Mega-Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD752FE}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD752D6}, game_version)", name: "Map (Deep Space)", prefix: "9" },
  { address: "version_choice({0x0, 0xD7530E}, game_version)", name: "Thundara", prefix: "9" },
  { address: "version_choice({0x0, 0xD75346}, game_version)", name: "Zero Gravira", prefix: "9" },
  { address: "version_choice({0x0, 0xD7534E}, game_version)", name: "Pulse Bomb", prefix: "9" },
  { address: "version_choice({0x0, 0xD7531E}, game_version)", name: "Chaos Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD75326}, game_version)", name: "Mine Shield", prefix: "9" },
  { address: "version_choice({0x0, 0xD75316}, game_version)", name: "Xehanort's Report 1", prefix: "9" },
  { address: "version_choice({0x0, 0xD7532E}, game_version)", name: "Mega Attack Recipe", prefix: "9" },
  { address: "version_choice({0x0, 0xD75336}, game_version)", name: "Fire Surge", prefix: "9" },
  { address: "version_choice({0x0, 0xD7533E}, game_version)", name: "Fleeting Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD75306}, game_version)", name: "Mega-Potion", prefix: "9" },
];
