export const ventusDwarf = [
  { address: "version_choice({0x0, 0xD7504E}, game_version)", name: "Payback Raid", prefix: "2" },
  { address: "version_choice({0x0, 0xD75096}, game_version)", name: "Panacea", prefix: "2" },
  { address: "version_choice({0x0, 0xD7508E}, game_version)", name: "Mini", prefix: "2" },
  { address: "version_choice({0x0, 0xD75056}, game_version)", name: "Soothing Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD7505E}, game_version)", name: "Shimmering Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD75066}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD7506E}, game_version)", name: "Ether", prefix: "2" },
  { address: "version_choice({0x0, 0xD75036}, game_version)", name: "Fire", prefix: "2" },
  { address: "version_choice({0x0, 0xD7503E}, game_version)", name: "Poison", prefix: "2" },
  { address: "version_choice({0x0, 0xD75046}, game_version)", name: "Map (Dwarf Woodlands)", prefix: "2" },
  { address: "version_choice({0x0, 0xD7509E}, game_version)", name: "Attack Recipe", prefix: "2" },
  { address: "version_choice({0x0, 0xD75076}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD7507E}, game_version)", name: "Ether", prefix: "2" },
  { address: "version_choice({0x0, 0xD75086}, game_version)", name: "Potion", prefix: "2" },
];
