export const ventusNeverland = [
  { address: "version_choice({0x0, 0xD75356}, game_version)", name: "Megalixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD7535E}, game_version)", name: "Mega-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD75366}, game_version)", name: "Ether", prefix: "B" },
  { address: "version_choice({0x0, 0xD7536E}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD75376}, game_version)", name: "Firaga", prefix: "B" },
  { address: "version_choice({0x0, 0xD7537E}, game_version)", name: "Treasure Raid", prefix: "B" },
  { address: "version_choice({0x0, 0xD75386}, game_version)", name: "Aeroga", prefix: "B" },
  { address: "version_choice({0x0, 0xD7538E}, game_version)", name: "Blitz", prefix: "B" },
  { address: "version_choice({0x0, 0xD75396}, game_version)", name: "Elixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD7539E}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD753A6}, game_version)", name: "Panacea", prefix: "B" },
  { address: "version_choice({0x0, 0xD753D6}, game_version)", name: "Balloon Letter", prefix: "B" },
  { address: "version_choice({0x0, 0xD753AE}, game_version)", name: "Mega-Ether", prefix: "B" },
  { address: "version_choice({0x0, 0xD753B6}, game_version)", name: "Fleeting Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD753BE}, game_version)", name: "Map (Neverland)", prefix: "B" },
  { address: "version_choice({0x0, 0xD753C6}, game_version)", name: "Abounding Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD753CE}, game_version)", name: "Megalixir", prefix: "B" },
];
