export const terraNeverland = [
  { address: "version_choice({0x0, 0xD74FEE}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD74FF6}, game_version)", name: "Ether", prefix: "B" },
  { address: "version_choice({0x0, 0xD74FFE}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD75006}, game_version)", name: "Mega-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD7500E}, game_version)", name: "Firaga", prefix: "B" },
  { address: "version_choice({0x0, 0xD75016}, game_version)", name: "Dark Haze", prefix: "B" },
  { address: "version_choice({0x0, 0xD7501E}, game_version)", name: "Geo Impact", prefix: "B" },
  { address: "version_choice({0x0, 0xD75026}, game_version)", name: "Elixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD7507E}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD7502E}, game_version)", name: "Shimmering Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD75036}, game_version)", name: "Mega Magic Recipe", prefix: "B" },
  { address: "version_choice({0x0, 0xD74FE6}, game_version)", name: "Map (Neverland)", prefix: "B" },
  { address: "version_choice({0x0, 0xD7503E}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD7506E}, game_version)", name: "Megalixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD75076}, game_version)", name: "Zero Graviga", prefix: "B" },
  { address: "version_choice({0x0, 0xD75046}, game_version)", name: "Abounding Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD7504E}, game_version)", name: "Panacea", prefix: "B" },
  { address: "version_choice({0x0, 0xD75056}, game_version)", name: "Megalixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD7505E}, game_version)", name: "Ars Solum", prefix: "B" },
  { address: "version_choice({0x0, 0xD75066}, game_version)", name: "Chaos Crystal", prefix: "B" },
];
