export const terraRadiant = [
  { address: "version_choice({0x0, 0xD75656}, game_version)", name: "Fira", prefix: "6" },
  { address: "version_choice({0x0, 0xD7565E}, game_version)", name: "Pulsing Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD75666}, game_version)", name: "Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD7566E}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD7563E}, game_version)", name: "Esuna", prefix: "6" },
  { address: "version_choice({0x0, 0xD75646}, game_version)", name: "Blackout", prefix: "6" },
  { address: "version_choice({0x0, 0xD7564E}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD75686}, game_version)", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "version_choice({0x0, 0xD7569E}, game_version)", name: "Panacea", prefix: "6" },
  { address: "version_choice({0x0, 0xD7568E}, game_version)", name: "Thunder Surge", prefix: "6" },
  { address: "version_choice({0x0, 0xD75696}, game_version)", name: "Fleeting Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD756A6}, game_version)", name: "Shimmering Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD75676}, game_version)", name: "Mega-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD7567E}, game_version)", name: "Chaos Crystal", prefix: "6" },
];
