export const terraDisney = [
  { address: "version_choice({0x0, 0xD74EAE}, game_version)", name: "Map (Disney Town)", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EB6}, game_version)", name: "Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EBE}, game_version)", name: "Abounding Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EC6}, game_version)", name: "Payback Fang", prefix: "C" },
  { address: "version_choice({0x0, 0xD74ECE}, game_version)", name: "Slot Edge", prefix: "C" },
  { address: "version_choice({0x0, 0xD74ED6}, game_version)", name: "Panacea", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EDE}, game_version)", name: "Action Recipe", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EE6}, game_version)", name: "Chaos Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EEE}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EF6}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD74F0E}, game_version)", name: "Absolute Zero", prefix: "C" },
  { address: "version_choice({0x0, 0xD74F26}, game_version)", name: "Mega-Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD74EFE}, game_version)", name: "Zero Gravira", prefix: "C" },
  { address: "version_choice({0x0, 0xD74F06}, game_version)", name: "Aerial Slam", prefix: "C" },
  { address: "version_choice({0x0, 0xD74F16}, game_version)", name: "Break Time", prefix: "C" },
  { address: "version_choice({0x0, 0xD74F1E}, game_version)", name: "Chaos Crystal", prefix: "C" },
];
