export const terraSpace = [
  { address: "version_choice({0x0, 0xD74F4E}, game_version)", name: "High Jump", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F86}, game_version)", name: "Brutal Blast", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F8E}, game_version)", name: "Pulsing Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F96}, game_version)", name: "Mega-Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FAE}, game_version)", name: "Mega-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FBE}, game_version)", name: "Map (Deep Space)", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F56}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F5E}, game_version)", name: "Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F66}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F6E}, game_version)", name: "Pulsing Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F76}, game_version)", name: "Warp", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F7E}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD74F9E}, game_version)", name: "Hungry Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FD6}, game_version)", name: "Mega-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FDE}, game_version)", name: "Fleeting Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FB6}, game_version)", name: "Thundara", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FC6}, game_version)", name: "Abounding Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FCE}, game_version)", name: "Wellspring Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD74FA6}, game_version)", name: "Mine Square", prefix: "9" },
];
