export const terraDwarf = [
  { address: "version_choice({0x0, 0xD7555E}, game_version)", name: "Balloon Letter", prefix: "2" },
  { address: "version_choice({0x0, 0xD75566}, game_version)", name: "Ether", prefix: "2" },
  { address: "version_choice({0x0, 0xD7556E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD75576}, game_version)", name: "Flame Salvo", prefix: "2" },
  { address: "version_choice({0x0, 0xD7557E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD75586}, game_version)", name: "Block Recipe", prefix: "2" },
  { address: "version_choice({0x0, 0xD7558E}, game_version)", name: "Poison Edge", prefix: "2" },
  { address: "version_choice({0x0, 0xD755B6}, game_version)", name: "Fire", prefix: "2" },
  { address: "version_choice({0x0, 0xD75596}, game_version)", name: "Fission Firaga", prefix: "2" },
  { address: "version_choice({0x0, 0xD7559E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD755AE}, game_version)", name: "Map (Dwarf Woodlands)", prefix: "2" },
  { address: "version_choice({0x0, 0xD755BE}, game_version)", name: "Soothing Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD755A6}, game_version)", name: "Hungry Crystal", prefix: "2" },
];
