export const terraDwarf = [
  { address: "version_choice({0x0, 0xD74D5E}, game_version)", name: "Balloon Letter", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D66}, game_version)", name: "Ether", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D6E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D76}, game_version)", name: "Flame Salvo", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D7E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D86}, game_version)", name: "Block Recipe", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D8E}, game_version)", name: "Poison Edge", prefix: "2" },
  { address: "version_choice({0x0, 0xD74DB6}, game_version)", name: "Fire", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D96}, game_version)", name: "Fission Firaga", prefix: "2" },
  { address: "version_choice({0x0, 0xD74D9E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD74DAE}, game_version)", name: "Map (Dwarf Woodlands)", prefix: "2" },
  { address: "version_choice({0x0, 0xD74DBE}, game_version)", name: "Soothing Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD74DA6}, game_version)", name: "Hungry Crystal", prefix: "2" },
];
