export const terraSpace = [
  { address: "version_choice({0x0, 0xD7574E}, game_version)", name: "High Jump", prefix: "9" },
  { address: "version_choice({0x0, 0xD75786}, game_version)", name: "Brutal Blast", prefix: "9" },
  { address: "version_choice({0x0, 0xD7578E}, game_version)", name: "Pulsing Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD75796}, game_version)", name: "Mega-Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD757AE}, game_version)", name: "Mega-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD757BE}, game_version)", name: "Map (Deep Space)", prefix: "9" },
  { address: "version_choice({0x0, 0xD75756}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD7575E}, game_version)", name: "Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD75766}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD7576E}, game_version)", name: "Pulsing Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD75776}, game_version)", name: "Warp", prefix: "9" },
  { address: "version_choice({0x0, 0xD7577E}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD7579E}, game_version)", name: "Hungry Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD757D6}, game_version)", name: "Mega-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD757DE}, game_version)", name: "Fleeting Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD757B6}, game_version)", name: "Thundara", prefix: "9" },
  { address: "version_choice({0x0, 0xD757C6}, game_version)", name: "Abounding Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD757CE}, game_version)", name: "Wellspring Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD757A6}, game_version)", name: "Mine Square", prefix: "9" },
];
