export const terraNeverland = [
  { address: "version_choice({0x0, 0xD757EE}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD757F6}, game_version)", name: "Ether", prefix: "B" },
  { address: "version_choice({0x0, 0xD757FE}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD75806}, game_version)", name: "Mega-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD7580E}, game_version)", name: "Firaga", prefix: "B" },
  { address: "version_choice({0x0, 0xD75816}, game_version)", name: "Dark Haze", prefix: "B" },
  { address: "version_choice({0x0, 0xD7581E}, game_version)", name: "Geo Impact", prefix: "B" },
  { address: "version_choice({0x0, 0xD75826}, game_version)", name: "Elixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD7587E}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD7582E}, game_version)", name: "Shimmering Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD75836}, game_version)", name: "Mega Magic Recipe", prefix: "B" },
  { address: "version_choice({0x0, 0xD757E6}, game_version)", name: "Map (Neverland)", prefix: "B" },
  { address: "version_choice({0x0, 0xD7583E}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD7586E}, game_version)", name: "Megalixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD75876}, game_version)", name: "Zero Graviga", prefix: "B" },
  { address: "version_choice({0x0, 0xD75846}, game_version)", name: "Abounding Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD7584E}, game_version)", name: "Panacea", prefix: "B" },
  { address: "version_choice({0x0, 0xD75856}, game_version)", name: "Megalixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD7585E}, game_version)", name: "Ars Solum", prefix: "B" },
  { address: "version_choice({0x0, 0xD75866}, game_version)", name: "Chaos Crystal", prefix: "B" },
];
