export const terraRadiant = [
  { address: "version_choice({0x0, 0xD74E56}, game_version)", name: "Fira", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E5E}, game_version)", name: "Pulsing Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E66}, game_version)", name: "Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E6E}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E3E}, game_version)", name: "Esuna", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E46}, game_version)", name: "Blackout", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E4E}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E86}, game_version)", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E9E}, game_version)", name: "Panacea", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E8E}, game_version)", name: "Thunder Surge", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E96}, game_version)", name: "Fleeting Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD74EA6}, game_version)", name: "Shimmering Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E76}, game_version)", name: "Mega-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD74E7E}, game_version)", name: "Chaos Crystal", prefix: "6" },
];
