export const terraDisney = [
  { address: "version_choice({0x0, 0xD756AE}, game_version)", name: "Map (Disney Town)", prefix: "C" },
  { address: "version_choice({0x0, 0xD756B6}, game_version)", name: "Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD756BE}, game_version)", name: "Abounding Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD756C6}, game_version)", name: "Payback Fang", prefix: "C" },
  { address: "version_choice({0x0, 0xD756CE}, game_version)", name: "Slot Edge", prefix: "C" },
  { address: "version_choice({0x0, 0xD756D6}, game_version)", name: "Panacea", prefix: "C" },
  { address: "version_choice({0x0, 0xD756DE}, game_version)", name: "Action Recipe", prefix: "C" },
  { address: "version_choice({0x0, 0xD756E6}, game_version)", name: "Chaos Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD756EE}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD756F6}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD7570E}, game_version)", name: "Absolute Zero", prefix: "C" },
  { address: "version_choice({0x0, 0xD75726}, game_version)", name: "Mega-Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD756FE}, game_version)", name: "Zero Gravira", prefix: "C" },
  { address: "version_choice({0x0, 0xD75706}, game_version)", name: "Aerial Slam", prefix: "C" },
  { address: "version_choice({0x0, 0xD75716}, game_version)", name: "Break Time", prefix: "C" },
  { address: "version_choice({0x0, 0xD7571E}, game_version)", name: "Chaos Crystal", prefix: "C" },
];
