const dlinkAbilitySlots = [
  { address: "version_choice({0x0, 0x817654}, game_version)", name: "Ventus Haste", prefix: "" },
  { address: "version_choice({0x0, 0x817656}, game_version)", name: "Ventus Auto-Counter", prefix: "" },
  { address: "version_choice({0x0, 0x817658}, game_version)", name: "Aqua Magic Deflector", prefix: "" },
  { address: "version_choice({0x0, 0x81765A}, game_version)", name: "Aqua Auto-Life", prefix: "" },
  { address: "version_choice({0x0, 0x81765C}, game_version)", name: "Terra Overdrive", prefix: "" },
  { address: "version_choice({0x0, 0x81765E}, game_version)", name: "Terra Auto-Block", prefix: "" },
  { address: "version_choice({0x0, 0x817660}, game_version)", name: "Mickey Auto-Teleport", prefix: "" },
  { address: "version_choice({0x0, 0x817662}, game_version)", name: "Mickey Double EXP", prefix: "" },
  { address: "version_choice({0x0, 0x817664}, game_version)", name: "Donald Magic Boost", prefix: "" },
  { address: "version_choice({0x0, 0x817666}, game_version)", name: "Donald Shell", prefix: "" },
  { address: "version_choice({0x0, 0x817668}, game_version)", name: "Goofy Protect", prefix: "" },
  { address: "version_choice({0x0, 0x81766A}, game_version)", name: "Goofy Stun Boost", prefix: "" },
  { address: "version_choice({0x0, 0x81766C}, game_version)", name: "Snow White Gauge Boost", prefix: "" },
  { address: "version_choice({0x0, 0x81766E}, game_version)", name: "Snow White Quick Reload", prefix: "" },
  { address: "version_choice({0x0, 0x817670}, game_version)", name: "Cinderella Auto-Remedy", prefix: "" },
  { address: "version_choice({0x0, 0x817672}, game_version)", name: "Cinderella Regen", prefix: "" },
  { address: "version_choice({0x0, 0x817674}, game_version)", name: "Maleficent Focus Saver", prefix: "" },
  { address: "version_choice({0x0, 0x817676}, game_version)", name: "Maleficent Drain", prefix: "" },
  { address: "version_choice({0x0, 0x817678}, game_version)", name: "Zack Berserk", prefix: "" },
  { address: "version_choice({0x0, 0x81767A}, game_version)", name: "Zack Attack Deflector", prefix: "" },
  { address: "version_choice({0x0, 0x81767C}, game_version)", name: "Stitch Attack Boost", prefix: "" },
  { address: "version_choice({0x0, 0x81767E}, game_version)", name: "Stitch Double CP", prefix: "" },
  { address: "version_choice({0x0, 0x817680}, game_version)", name: "Peter Pan Float", prefix: "" },
  { address: "version_choice({0x0, 0x817682}, game_version)", name: "Peter Pan Double Strike", prefix: "" },
  { address: "version_choice({0x0, 0x817684}, game_version)", name: "Pete Munny Plus", prefix: "" },
  { address: "version_choice({0x0, 0x817686}, game_version)", name: "Pete Steal", prefix: "" },
];

export const dlinkAbilityLocations = [...dlinkAbilitySlots];
