export const aquaRadiant = [
  { address: "version_choice({0x0, 0xD75256}, game_version)", name: "Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD7525E}, game_version)", name: "Ether", prefix: "6" },
  { address: "version_choice({0x0, 0xD75266}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD7526E}, game_version)", name: "Thundara", prefix: "6" },
  { address: "version_choice({0x0, 0xD75276}, game_version)", name: "Hi-Potion", prefix: "6" },
  { address: "version_choice({0x0, 0xD752A6}, game_version)", name: "Block Recipe", prefix: "6" },
  { address: "version_choice({0x0, 0xD7524E}, game_version)", name: "Counter Blast", prefix: "6" },
  { address: "version_choice({0x0, 0xD752AE}, game_version)", name: "Soothing Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD752C6}, game_version)", name: "Xehanort's Report 3", prefix: "6" },
  { address: "version_choice({0x0, 0xD7527E}, game_version)", name: "Zero Gravity", prefix: "6" },
  { address: "version_choice({0x0, 0xD75286}, game_version)", name: "Wellspring Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD7528E}, game_version)", name: "Strike Raid", prefix: "6" },
  { address: "version_choice({0x0, 0xD75296}, game_version)", name: "Fleeting Crystal", prefix: "6" },
  { address: "version_choice({0x0, 0xD7529E}, game_version)", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "version_choice({0x0, 0xD752BE}, game_version)", name: "Panacea", prefix: "6" },
  { address: "version_choice({0x0, 0xD752B6}, game_version)", name: "Mine Square", prefix: "6" },
];
