export const aquaSpace = [
  { address: "version_choice({0x0, 0xD75376}, game_version)", name: "Teleport", prefix: "9" },
  { address: "version_choice({0x0, 0xD7539E}, game_version)", name: "Blitz", prefix: "9" },
  { address: "version_choice({0x0, 0xD753A6}, game_version)", name: "Abounding Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD753AE}, game_version)", name: "Mega-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD7537E}, game_version)", name: "Map (Deep Space)", prefix: "9" },
  { address: "version_choice({0x0, 0xD75386}, game_version)", name: "Hi-Potion", prefix: "9" },
  { address: "version_choice({0x0, 0xD7538E}, game_version)", name: "Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD75396}, game_version)", name: "Balloon Letter", prefix: "9" },
  { address: "version_choice({0x0, 0xD753D6}, game_version)", name: "Fire Surge", prefix: "9" },
  { address: "version_choice({0x0, 0xD753DE}, game_version)", name: "Prism Rain", prefix: "9" },
  { address: "version_choice({0x0, 0xD753B6}, game_version)", name: "Zero Gravira", prefix: "9" },
  { address: "version_choice({0x0, 0xD753C6}, game_version)", name: "Hungry Crystal", prefix: "9" },
  { address: "version_choice({0x0, 0xD753CE}, game_version)", name: "Mega-Ether", prefix: "9" },
  { address: "version_choice({0x0, 0xD753BE}, game_version)", name: "Mega Attack Recipe", prefix: "9" },
];
