export const aquaDisney = [
  { address: "version_choice({0x0, 0xD752CE}, game_version)", name: "Map (Disney Town)", prefix: "C" },
  { address: "version_choice({0x0, 0xD752D6}, game_version)", name: "Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD752DE}, game_version)", name: "Abouding Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD752E6}, game_version)", name: "Fira", prefix: "C" },
  { address: "version_choice({0x0, 0xD752EE}, game_version)", name: "Slot Edge", prefix: "C" },
  { address: "version_choice({0x0, 0xD752F6}, game_version)", name: "Hungry Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD752FE}, game_version)", name: "Mega-Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD75306}, game_version)", name: "Chaos Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD7530E}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD75316}, game_version)", name: "Thunder", prefix: "C" },
  { address: "version_choice({0x0, 0xD75346}, game_version)", name: "Pulsing Crystal", prefix: "C" },
  { address: "version_choice({0x0, 0xD7532E}, game_version)", name: "Mega-Potion", prefix: "C" },
  { address: "version_choice({0x0, 0xD7531E}, game_version)", name: "Panacea", prefix: "C" },
  { address: "version_choice({0x0, 0xD7534E}, game_version)", name: "Action Recipe", prefix: "C" },
  { address: "version_choice({0x0, 0xD75326}, game_version)", name: "Aerial Slam", prefix: "C" },
  { address: "version_choice({0x0, 0xD75336}, game_version)", name: "Break Time", prefix: "C" },
  { address: "version_choice({0x0, 0xD7533E}, game_version)", name: "Soothing Crystal", prefix: "C" },
];
