export const aquaNeverland = [
  { address: "version_choice({0x0, 0xD753E6}, game_version)", name: "Firaga Burst", prefix: "B" },
  { address: "version_choice({0x0, 0xD753EE}, game_version)", name: "Elixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD753F6}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD753FE}, game_version)", name: "Ether", prefix: "B" },
  { address: "version_choice({0x0, 0xD75446}, game_version)", name: "Hi-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD75406}, game_version)", name: "Mine Shield", prefix: "B" },
  { address: "version_choice({0x0, 0xD7540E}, game_version)", name: "Elixir", prefix: "B" },
  { address: "version_choice({0x0, 0xD75416}, game_version)", name: "Map (Neverland)", prefix: "B" },
  { address: "version_choice({0x0, 0xD7541E}, game_version)", name: "Mega-Potion", prefix: "B" },
  { address: "version_choice({0x0, 0xD75426}, game_version)", name: "Panacea", prefix: "B" },
  { address: "version_choice({0x0, 0xD7544E}, game_version)", name: "Fleeting Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD7542E}, game_version)", name: "Time Splicer", prefix: "B" },
  { address: "version_choice({0x0, 0xD7543E}, game_version)", name: "Thundaga", prefix: "B" },
  { address: "version_choice({0x0, 0xD75456}, game_version)", name: "Chaos Crystal", prefix: "B" },
  { address: "version_choice({0x0, 0xD7545E}, game_version)", name: "Firaga", prefix: "B" },
  { address: "version_choice({0x0, 0xD75436}, game_version)", name: "Mega-Ether", prefix: "B" },
];
