export const aquaDwarf = [
  { address: "version_choice({0x0, 0xD7515E}, game_version)", name: "Balloon Letter", prefix: "2" },
  { address: "version_choice({0x0, 0xD75166}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD7516E}, game_version)", name: "Shimmering Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD75176}, game_version)", name: "Magnet", prefix: "2" },
  { address: "version_choice({0x0, 0xD7517E}, game_version)", name: "Shimmering Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD75186}, game_version)", name: "Fleeting Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD7518E}, game_version)", name: "Fire", prefix: "2" },
  { address: "version_choice({0x0, 0xD75196}, game_version)", name: "Fission Firaga", prefix: "2" },
  { address: "version_choice({0x0, 0xD7519E}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD751AE}, game_version)", name: "Map (Dwarf Woodlands)", prefix: "2" },
  { address: "version_choice({0x0, 0xD751CE}, game_version)", name: "Fleeting Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD751A6}, game_version)", name: "Hungry Crystal", prefix: "2" },
  { address: "version_choice({0x0, 0xD751B6}, game_version)", name: "Hi-Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD751BE}, game_version)", name: "Ether", prefix: "2" },
  { address: "version_choice({0x0, 0xD751C6}, game_version)", name: "Potion", prefix: "2" },
  { address: "version_choice({0x0, 0xD7514E}, game_version)", name: "Payback Surge", prefix: "2" },
  { address: "version_choice({0x0, 0xD75156}, game_version)", name: "Poison", prefix: "2" },
  { address: "version_choice({0x0, 0xD751D6}, game_version)", name: "Attack Recipe", prefix: "2" },
];
