export const aquaEnchanted = [
  { address: "version_choice({0x0, 0xD7523E}, game_version)", name: "Map (Enchanted Dominion)", prefix: "4" },
  { address: "version_choice({0x0, 0xD751DE}, game_version)", name: "Absolute Zero", prefix: "4" },
  { address: "version_choice({0x0, 0xD751E6}, game_version)", name: "Wellspring Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD751EE}, game_version)", name: "Cure", prefix: "4" },
  { address: "version_choice({0x0, 0xD751F6}, game_version)", name: "Pulsing Crystal", prefix: "4" },
  { address: "version_choice({0x0, 0xD75246}, game_version)", name: "Sleep", prefix: "4" },
  { address: "version_choice({0x0, 0xD751FE}, game_version)", name: "Confusion Strike", prefix: "4" },
  { address: "version_choice({0x0, 0xD75206}, game_version)", name: "Hi-Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD7520E}, game_version)", name: "Ice Barrage", prefix: "4" },
  { address: "version_choice({0x0, 0xD75216}, game_version)", name: "Hi-Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD7521E}, game_version)", name: "Ether", prefix: "4" },
  { address: "version_choice({0x0, 0xD75226}, game_version)", name: "Balloon Letter", prefix: "4" },
  { address: "version_choice({0x0, 0xD7522E}, game_version)", name: "Potion", prefix: "4" },
  { address: "version_choice({0x0, 0xD75236}, game_version)", name: "Hi-Potion", prefix: "4" },
];
